name: deploy gds-api-test

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: run esLint
        run: npm run lint

  test:
    name: run unit tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    name: build project
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: install dependencies
        run: npm install

      - name: build
        run: npx tsc

#  deploy:
#    name: deploy to Azure
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@v2

#      - name: setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20'

#      - name: install dependencies
#        run: npm install

#     - name: build
#        run: npx tsc

#     - name: deploy to azure web app
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ secrets.AZURE_APP_NAME }}
#          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#          package: .